name: test 2023

on:
  push:
    branches:
      - master
    paths:
      - '2023/**'

jobs:
  test:
    name: Aoc 2023 Tests | OTP 26.1.2 | Elixir 1.16.0-rc.0
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: 2023
    env:
      name: test
      AOC_SESSION_COOKIE: ${{ secrets.AOC_SESSION_COOKIE }}
      MIX_ENV: test

    steps:
      - uses: actions/checkout@v3
      - uses: erlef/setup-beam@v1
        with:
          otp-version: 26.1.2
          elixir-version: 1.16.0-rc.0

      - name: Format
        run: mix format --check-formatted

      - name: Dependencies
        run: |
          mix local.rebar --force
          mix local.hex --force
          mix deps.get

      - name: Compile
        run: mix compile --warnings-as-errors

      - name: Test
        run: mix test --trace --warnings-as-errors
